use_frameworks!

platform :ios, '9.0'

target 'SERichTextEditor_Example' do
  pod 'SERichTextEditor', :path => '../'

  target 'SERichTextEditor_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase'
  end
end
